/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Rest.test.main;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}